# general configuration
url: http://www.tsendeemts.com
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/my-pic.jpg"
  # author will appear under the avatar (optional)
  author: "Tsendsuren Munkhdalai"
  # tagline will appear under the title (optional)
  tagline: "<p>
      I am a researcher at Microsoft Research Montreal.
      I spent two years at the University of Massachusetts as a postdoc sitting right next to the neurology department. 
      I got my MSc and PhD under the excellent supervision of Prof. Keun Ho Ryu from the Department of Computer Science at Chungbuk National University, South Korea.
      I studied my bachelor in Ulaanbaatar, Mongolia at the National University of Mongolia where my thesis topic was on demand forcasting with regression analysis.
    </p>
    <p>
      My current research focus is on meta-learning, memory and attention systems, rapid and temporal adaptations and learning feedbacks in artificial neural networks.
    </p>
    <p>
      As a graduate student, I had a chance to work for a couple of startups where we focused on personalized document processing pipeline and search engine at scale. I also used to participate in Kaggle competitions and held the competitions expert badge from the Kaggle community.
    </p>
    <p>
      A few sport activities I attemp to do are weight training, volleyball and swimming. I also like to have beer while playing pool and discussing ideas and technology.
    </p>"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true
